/* eslint-disable */
/**
 * Generated by `cargo xtask typegen` from harness/core/crates/orrery-proto.
 * Do not edit by hand: CI regenerates this file and fails on a diff.
 */

export type Event =
  | {
      /**
       * Where this sits in the session's order.
       */
      seq: Seq;
      t: "turn.started";
      /**
       * Which turn.
       */
      turn: TurnId;
      [k: string]: unknown;
    }
  | {
      /**
       * How it changed.
       */
      patch: SurfacePatch;
      /**
       * Where this sits in the session's order.
       */
      seq: Seq;
      /**
       * Which surface.
       */
      surface: SurfaceId;
      t: "delta";
      [k: string]: unknown;
    }
  | {
      /**
       * Which call.
       */
      call: CallId;
      /**
       * Which tool.
       */
      ref: ToolRef;
      /**
       * Where this sits in the session's order.
       */
      seq: Seq;
      t: "tool.started";
      [k: string]: unknown;
    }
  | {
      /**
       * Which call.
       */
      call: CallId;
      /**
       * How it went.
       */
      outcome: Outcome;
      /**
       * Where this sits in the session's order.
       */
      seq: Seq;
      t: "tool.settled";
      [k: string]: unknown;
    }
  | {
      /**
       * How long there is to answer before the default applies.
       */
      deadline_ms: number;
      /**
       * The question.
       */
      prompt: ConsentPrompt;
      /**
       * Where this sits in the session's order.
       */
      seq: Seq;
      t: "consent.request";
      [k: string]: unknown;
    }
  | {
      /**
       * Where this sits in the session's order.
       */
      seq: Seq;
      t: "turn.settled";
      /**
       * Which turn.
       */
      turn: TurnId;
      /**
       * What it cost.
       */
      usage: Usage;
      [k: string]: unknown;
    }
  | {
      /**
       * What went wrong.
       */
      detail: ErrorDetail;
      /**
       * How far it reaches.
       */
      scope: ErrorScope;
      /**
       * Where this sits in the session's order.
       */
      seq: Seq;
      t: "error";
      [k: string]: unknown;
    };
export type Seq = number;
export type TurnId = string;
/**
 * A change to a surface already on screen.
 *
 * The whole point of the surface protocol: a streaming tool sends one [`SurfacePatch::Append`] per chunk rather than a whole new surface, so the hot path is a string and not a tree.
 */
export type SurfacePatch =
  | {
      /**
       * Which surface.
       */
      id: SurfaceId;
      op: "replace";
      /**
       * What it becomes.
       */
      value: Surface;
      [k: string]: unknown;
    }
  | {
      /**
       * Which surface.
       */
      id: SurfaceId;
      op: "append";
      /**
       * What to add.
       */
      text: string;
      [k: string]: unknown;
    }
  | {
      /**
       * Which surface.
       */
      id: SurfaceId;
      op: "set";
      /**
       * The path from the surface's root to the field.
       */
      path: string[];
      /**
       * The new value.
       */
      value: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      /**
       * Which surface.
       */
      id: SurfaceId;
      op: "remove";
      [k: string]: unknown;
    };
export type SurfaceId = string;
/**
 * What a surface *is*.
 */
export type SurfaceKind =
  | {
      /**
       * How it is meant.
       */
      style?: TextStyle | null;
      t: "text";
      /**
       * The text.
       */
      value: string;
      [k: string]: unknown;
    }
  | {
      /**
       * The header row.
       */
      columns: string[];
      /**
       * The body. Every row is expected to be `columns.len()` long.
       */
      rows?: Cell[][];
      t: "table";
      [k: string]: unknown;
    }
  | {
      /**
       * The roots.
       */
      nodes?: TreeNode[];
      t: "tree";
      [k: string]: unknown;
    }
  | {
      /**
       * The changed regions.
       */
      hunks?: Hunk[];
      /**
       * The file.
       */
      path: string;
      t: "diff";
      [k: string]: unknown;
    }
  | {
      /**
       * How much is done.
       */
      done?: number | null;
      /**
       * What is happening.
       */
      label: string;
      t: "progress";
      /**
       * How much there is.
       */
      total?: number | null;
      [k: string]: unknown;
    }
  | {
      /**
       * Which channel: `stdout`, `stderr`, a log name.
       */
      id: string;
      t: "stream";
      [k: string]: unknown;
    }
  | {
      /**
       * The entries.
       */
      items?: TaskItem[];
      t: "task";
      [k: string]: unknown;
    }
  | {
      /**
       * The offered answers.
       */
      choices?: Choice[];
      /**
       * How long there is to answer.
       */
      deadline_ms?: number | null;
      /**
       * What is used if the deadline passes.
       */
      default?: string | null;
      /**
       * Whether an answer outside `choices` is accepted.
       */
      free: boolean;
      /**
       * Whether more than one may be picked.
       */
      multi: boolean;
      /**
       * What is being asked.
       */
      prompt: string;
      t: "question";
      [k: string]: unknown;
    }
  | {
      /**
       * The inputs.
       */
      fields?: Field[];
      /**
       * The submit button's label.
       */
      submit: string;
      t: "form";
      [k: string]: unknown;
    }
  | {
      /**
       * The contents.
       */
      children?: Surface[];
      /**
       * Whether it starts folded.
       */
      collapsed: boolean;
      /**
       * Which way.
       */
      dir: StackDir;
      t: "stack";
      /**
       * An optional heading.
       */
      title?: string | null;
      [k: string]: unknown;
    }
  | {
      /**
       * Whether the last patch has arrived.
       */
      complete: boolean;
      t: "markdown";
      /**
       * The source.
       */
      value: string;
      [k: string]: unknown;
    }
  | {
      /**
       * What to show instead, for a client that has no such renderer.
       *
       * Mandatory, and a `Box<Surface>` rather than an `Option`: a custom surface nobody can draw is a blank hole in a transcript, so the type refuses to express one.
       */
      fallback: Surface;
      /**
       * `<ext>.<name>`, so two extensions cannot claim one renderer.
       */
      kind: string;
      /**
       * Whatever that renderer needs.
       */
      payload: {
        [k: string]: unknown;
      };
      t: "custom";
      [k: string]: unknown;
    };
/**
 * A hint about how a run of text is meant, never a colour.
 */
export type TextStyle = "plain" | "muted" | "emphasis" | "code" | "error" | "success" | "warning";
/**
 * What a line of a diff is.
 */
export type DiffLineKind = "context" | "add" | "remove";
/**
 * How far along whatever produced this surface is.
 */
export type Status = "pending" | "running" | "done" | "failed" | "cancelled";
/**
 * What a [`Field`] collects.
 */
export type FieldKind =
  | {
      t: "text";
      [k: string]: unknown;
    }
  | {
      t: "secret";
      [k: string]: unknown;
    }
  | {
      t: "number";
      [k: string]: unknown;
    }
  | {
      t: "bool";
      [k: string]: unknown;
    }
  | {
      /**
       * The options.
       */
      choices: Choice[];
      t: "choice";
      [k: string]: unknown;
    };
/**
 * Which way a [`SurfaceKind::Stack`] lays its children out.
 */
export type StackDir = "row" | "column";
export type CallId = string;
export type ToolRef = string;
/**
 * How something turned out.
 *
 * The type that makes "a denial is a value" real at every layer: the tool registry returns it, the transcript stores it, the wire carries it, the renderer draws it. Nothing anywhere raises a denial as an error, because an error would have to be rendered by whoever caught it, and then two layers would be describing the same refusal in two different ways.
 */
export type Outcome =
  | {
      /**
       * What to show, when there is something to show.
       */
      surface?: Surface | null;
      t: "ok";
      /**
       * What to feed back to the model, when that differs from what is shown.
       */
      value?: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      /**
       * Why, in words a person can act on.
       */
      reason: string;
      /**
       * Which rule.
       */
      rule: RuleId;
      t: "denied";
      [k: string]: unknown;
    }
  | {
      /**
       * How much was produced.
       */
      bytes_emitted: number;
      /**
       * How much was allowed.
       */
      limit: number;
      /**
       * What there is of it.
       */
      surface?: Surface | null;
      t: "truncated";
      [k: string]: unknown;
    }
  | {
      /**
       * Why.
       */
      reason: CancelReason;
      t: "cancelled";
      [k: string]: unknown;
    }
  | {
      /**
       * Which extension.
       */
      ext: ExtId;
      t: "unloaded";
      [k: string]: unknown;
    }
  | {
      /**
       * A stable, machine-readable code.
       */
      code: string;
      /**
       * What went wrong, in words.
       */
      message: string;
      t: "failed";
      [k: string]: unknown;
    };
export type RuleId = string;
/**
 * Why something stopped early.
 */
export type CancelReason = "user" | "budget" | "timeout" | "shutdown" | "parent";
export type ExtId = string;
/**
 * What a capability is *about*.
 *
 * The wire names are pinned per variant rather than derived, because two of them (`mem.read`, `mem.write`) are dotted and no `rename_all` rule produces a dot.
 */
export type Aspect =
  | "tool"
  | "mcp"
  | "skill"
  | "ext"
  | "mode"
  | "read"
  | "write"
  | "spawn"
  | "net"
  | "creds"
  | "ui"
  | "render"
  | "mem.read"
  | "mem.write";
export type PromptId = string;
export type Subject = string;
/**
 * How far an error reaches.
 */
export type ErrorScope = "transport" | "session" | "turn" | "tool" | "ext";
/**
 * How often the user has to be asked.
 *
 * Ordered `Never < Once < Always`, and narrowing takes the minimum: a child that asks every time cannot be promoted to a child that never asks.
 */
export type Consent = "always" | "once" | "never";
/**
 * The result of trying to load one extension.
 */
export type LoadOutcome =
  | {
      /**
       * What it added.
       */
      contributions?: Contribution[];
      /**
       * Which extension.
       */
      ext: ExtId;
      /**
       * How long it took.
       */
      ms: number;
      status: "ok";
      [k: string]: unknown;
    }
  | {
      /**
       * What it did add.
       */
      contributions?: Contribution[];
      /**
       * Which extension.
       */
      ext: ExtId;
      /**
       * How long it took.
       */
      ms: number;
      /**
       * What is missing, in words a person can act on.
       */
      problems?: string[];
      status: "degraded";
      [k: string]: unknown;
    }
  | {
      /**
       * Which extension.
       */
      ext: ExtId;
      /**
       * Why not.
       */
      reason: SkipReason;
      status: "skipped";
      [k: string]: unknown;
    }
  | {
      /**
       * Which extension.
       */
      ext: ExtId;
      /**
       * What went wrong.
       */
      message: string;
      /**
       * How far it got.
       */
      stage: LoadStage;
      status: "failed";
      [k: string]: unknown;
    };
/**
 * The kinds of thing an extension can contribute.
 */
export type ContributionKind =
  | "tool"
  | "provider"
  | "renderer"
  | "command"
  | "skill"
  | "memory"
  | "grader"
  | "router"
  | "session-store"
  | "mode"
  | "view";
/**
 * Why an extension was not loaded at all.
 *
 * A **closed** set. "It did not load" is a thing a user has to be able to act on, and free text cannot be grouped, counted or matched against a rule.
 */
export type SkipReason = "disabled" | "unsupported" | "dependency-missing" | "policy-denied" | "already-loaded";
/**
 * How far loading got before it stopped.
 */
export type LoadStage = "manifest" | "resolve" | "link" | "activate" | "contribute";
/**
 * One piece of a message.
 */
export type ContentBlock =
  | {
      t: "text";
      /**
       * The text.
       */
      text: string;
      [k: string]: unknown;
    }
  | {
      /**
       * Base64, without a data-URL prefix.
       */
      data: string;
      /**
       * The IANA media type, e.g. `image/png`.
       */
      media_type: string;
      t: "image";
      [k: string]: unknown;
    }
  | {
      /**
       * The call this block opens.
       */
      call: CallId;
      /**
       * The arguments, already validated against the tool's schema.
       */
      input: {
        [k: string]: unknown;
      };
      /**
       * The fully-qualified tool name, `<ext>.<name>`.
       */
      name: string;
      t: "tool-use";
      [k: string]: unknown;
    }
  | {
      /**
       * The call this block closes.
       */
      call: CallId;
      /**
       * How it went.
       */
      outcome: Outcome;
      t: "tool-result";
      [k: string]: unknown;
    }
  | {
      t: "thinking";
      /**
       * The reasoning text.
       */
      text: string;
      [k: string]: unknown;
    };
/**
 * Who said it.
 */
export type MessageRole = "system" | "user" | "assistant";
/**
 * Client to kernel.
 *
 * Every variant carries an `id`, because every response has to name what it is answering. It is repeated per variant rather than lifted to a struct field because serde cannot express a struct-level field alongside an internally tagged enum — a test asserts that no variant lost it.
 *
 * The tags are **dotted** and spelled out one by one. No `rename_all` rule produces a dot, so an added variant without an explicit `rename` would show up as `turn-submit` instead of `turn.submit`; the tag test catches exactly that.
 */
export type Request =
  | {
      /**
       * The request id.
       */
      id: ReqId;
      /**
       * Which profile to build it from.
       */
      profile: string;
      t: "session.create";
      /**
       * The workspace root.
       */
      workspace: string;
      [k: string]: unknown;
    }
  | {
      /**
       * The request id.
       */
      id: ReqId;
      /**
       * Which session.
       */
      session: SessionId;
      /**
       * Replay from just after this. Absent means from the start.
       */
      since?: Seq | null;
      t: "session.attach";
      [k: string]: unknown;
    }
  | {
      /**
       * The request id.
       */
      id: ReqId;
      /**
       * What was submitted.
       */
      input: UserInput;
      /**
       * Which session.
       */
      session: SessionId;
      t: "turn.submit";
      [k: string]: unknown;
    }
  | {
      /**
       * The request id.
       */
      id: ReqId;
      /**
       * Which session.
       */
      session: SessionId;
      t: "turn.cancel";
      /**
       * Which turn.
       */
      turn: TurnId;
      [k: string]: unknown;
    }
  | {
      /**
       * The request id.
       */
      id: ReqId;
      /**
       * Which session.
       */
      session: SessionId;
      /**
       * Which surface.
       */
      surface: SurfaceId;
      t: "intent";
      /**
       * What the surface produced.
       */
      value: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      /**
       * The answer.
       */
      answer: ConsentAnswerKind;
      /**
       * The request id.
       */
      id: ReqId;
      /**
       * Which prompt.
       */
      prompt: PromptId;
      t: "consent.answer";
      [k: string]: unknown;
    }
  | {
      /**
       * Its arguments.
       */
      args?: {
        [k: string]: unknown;
      };
      /**
       * The request id.
       */
      id: ReqId;
      /**
       * The command's name.
       */
      name: string;
      /**
       * Which session.
       */
      session: SessionId;
      t: "command";
      [k: string]: unknown;
    }
  | {
      /**
       * The request id.
       */
      id: ReqId;
      /**
       * What is being asked about.
       */
      of: QueryOf;
      t: "query";
      [k: string]: unknown;
    };
export type ReqId = string;
export type SessionId = string;
export type BranchId = string;
/**
 * The answer to a [`ConsentPrompt`].
 *
 * Four answers, not two: "yes" and "yes, and stop asking" are different decisions, and so are "no" and "no, ever".
 */
export type ConsentAnswerKind = "allow-once" | "allow-always" | "deny" | "deny-always";
/**
 * What a [`Request::Query`] is asking about.
 */
export type QueryOf =
  | {
      t: "sessions";
      [k: string]: unknown;
    }
  | {
      /**
       * Which one.
       */
      session: SessionId;
      t: "session";
      [k: string]: unknown;
    }
  | {
      /**
       * Which session.
       */
      session: SessionId;
      t: "tools";
      [k: string]: unknown;
    }
  | {
      t: "extensions";
      [k: string]: unknown;
    }
  | {
      t: "profiles";
      [k: string]: unknown;
    };

/**
 * The root the schema is generated from.
 *
 * Every type a client has to name, reachable from one place. schemars walks it and emits each reachable type once, under `definitions`, so the field names here are an index and nothing ever serialises as a `Protocol`.
 */
export interface Protocol {
  budget: Budget;
  event: Event;
  grant: Grant;
  load_outcome: LoadOutcome;
  message: Message;
  request: Request;
  surface: Surface;
  surface_patch: SurfacePatch;
  tool_descriptor: ToolDescriptor;
  usage: Usage;
  [k: string]: unknown;
}
/**
 * What a turn is allowed to spend.
 */
export interface Budget {
  /**
   * How much money, in micro-USD. `None` means unmetered.
   */
  max_micro_usd?: number | null;
  /**
   * How many tokens, input and output together.
   */
  max_tokens: number;
  /**
   * How many kernel turns.
   */
  max_turns: number;
  /**
   * How long, in milliseconds of wall clock.
   */
  wall_clock_ms: number;
  [k: string]: unknown;
}
/**
 * A surface, with the handle a patch addresses it by and how far along it is.
 */
export interface Surface {
  /**
   * The handle. Absent for a surface nothing will ever patch.
   */
  id?: SurfaceId | null;
  /**
   * What it is.
   */
  kind: SurfaceKind;
  /**
   * How far along it is.
   */
  status?: Status | null;
  [k: string]: unknown;
}
/**
 * One cell of a [`SurfaceKind::Table`].
 */
export interface Cell {
  /**
   * How it is meant.
   */
  style?: TextStyle | null;
  /**
   * The cell's text, already formatted by whoever knows the units.
   */
  text: string;
  [k: string]: unknown;
}
/**
 * One node of a [`SurfaceKind::Tree`].
 */
export interface TreeNode {
  /**
   * Its children. A leaf has none.
   */
  children?: TreeNode[];
  /**
   * Whether the node starts open.
   */
  expanded: boolean;
  /**
   * A stable handle, when the client needs to address this node.
   */
  id?: string | null;
  /**
   * What to show.
   */
  label: string;
  [k: string]: unknown;
}
/**
 * One changed region of a file.
 */
export interface Hunk {
  /**
   * The lines.
   */
  lines?: DiffLine[];
  /**
   * How many lines it covers.
   */
  new_lines: number;
  /**
   * First line of the region in the new file, 1-based.
   */
  new_start: number;
  /**
   * How many lines it covered.
   */
  old_lines: number;
  /**
   * First line of the region in the old file, 1-based.
   */
  old_start: number;
  [k: string]: unknown;
}
/**
 * One line inside a [`Hunk`].
 */
export interface DiffLine {
  /**
   * Added, removed or unchanged.
   */
  kind: DiffLineKind;
  /**
   * The line itself, without its leading marker.
   */
  text: string;
  [k: string]: unknown;
}
/**
 * One entry of a [`SurfaceKind::Task`] list.
 */
export interface TaskItem {
  /**
   * A stable handle, so a patch can update one item.
   */
  id: string;
  /**
   * What to show.
   */
  label: string;
  /**
   * How far along it is.
   */
  status: Status;
  [k: string]: unknown;
}
/**
 * One option of a [`SurfaceKind::Question`] or of a choice [`Field`].
 */
export interface Choice {
  /**
   * What is shown.
   */
  label: string;
  /**
   * What is sent back on selection.
   */
  value: string;
  [k: string]: unknown;
}
/**
 * One input of a [`SurfaceKind::Form`].
 */
export interface Field {
  /**
   * What it starts as.
   */
  default?: string | null;
  /**
   * What it collects.
   */
  kind: FieldKind;
  /**
   * What is shown next to it.
   */
  label: string;
  /**
   * The key this field's value is submitted under.
   */
  name: string;
  /**
   * Whether the form can be submitted without it.
   */
  required: boolean;
  [k: string]: unknown;
}
/**
 * What is being asked for, and why.
 */
export interface ConsentPrompt {
  /**
   * What they want.
   */
  capabilities?: Capability[];
  /**
   * The handle an answer is matched to.
   */
  id: PromptId;
  /**
   * Why, in words a person can act on.
   */
  reason: string;
  /**
   * The rule that requires the ask, when one does.
   */
  rule?: RuleId | null;
  /**
   * Who is asking.
   */
  subject: Subject;
  /**
   * Something to show alongside the question — the diff that is about to be written, the command that is about to run.
   */
  surface?: Surface | null;
  [k: string]: unknown;
}
/**
 * One aspect and the scope it is granted over.
 *
 * An **empty** `scope` means unqualified: the whole aspect, not nothing. That is what makes an unscoped parent wider than a scoped child, which is the direction narrowing needs.
 */
export interface Capability {
  /**
   * What the capability is about.
   */
  aspect: Aspect;
  /**
   * The names or patterns it covers. Empty means unqualified.
   */
  scope?: string[];
  [k: string]: unknown;
}
/**
 * What was actually spent.
 */
export interface Usage {
  /**
   * Tokens served from a provider-side prompt cache.
   */
  cache_hits: number;
  /**
   * Tokens sent.
   */
  input_tokens: number;
  /**
   * Cost in micro-USD, when the provider reports one.
   */
  micro_usd?: number | null;
  /**
   * Tokens received.
   */
  output_tokens: number;
  [k: string]: unknown;
}
/**
 * What went wrong.
 */
export interface ErrorDetail {
  /**
   * A stable, machine-readable code: `provider.unavailable`, `ext.crashed`.
   */
  code: string;
  /**
   * Anything structured a client could use.
   */
  data?: {
    [k: string]: unknown;
  };
  /**
   * What went wrong, in words.
   */
  message: string;
  /**
   * Whether the same thing, tried again, might work.
   */
  retryable: boolean;
  [k: string]: unknown;
}
/**
 * What a subject is allowed to do.
 */
export interface Grant {
  /**
   * The capabilities, one entry per aspect-and-scope.
   */
  capabilities?: Capability[];
  /**
   * How often to ask.
   */
  consent: Consent;
  [k: string]: unknown;
}
/**
 * What an extension added to the session.
 *
 * `kind` is a plain enum here. The derive macro that keeps it in step with the extension's manifest — so that a manifest promising a tool and a crate contributing a renderer is a build error rather than a surprise — is the extension host's (plan 06).
 */
export interface Contribution {
  /**
   * What kind of thing it is.
   */
  kind: ContributionKind;
  /**
   * Its name, unqualified: the extension is already known.
   */
  name: string;
  [k: string]: unknown;
}
/**
 * One turn of the conversation.
 */
export interface Message {
  /**
   * What they said.
   */
  content?: ContentBlock[];
  /**
   * Who said it.
   */
  role: MessageRole;
  [k: string]: unknown;
}
/**
 * What a person submitted.
 */
export interface UserInput {
  /**
   * Anything else they attached: images, a pasted tool result.
   */
  attachments?: ContentBlock[];
  /**
   * Which branch of the turn tree to submit on. Absent means the current one; present means "re-run from here", which is how an edited turn forks rather than overwrites.
   */
  branch?: BranchId | null;
  /**
   * What they typed.
   */
  text: string;
  [k: string]: unknown;
}
/**
 * One tool, as it appears in a model request.
 *
 * A wire type, and therefore this crate's: the registry produces it from [`AgentScope`](crate::AgentScope), a provider serialises it into the prompt, and the model is shown it. Both sides naming the same struct is what stops the two halves drifting — there used to be a copy in `orrery-provider` and a second in `orrery-tools`, with no conversion between them.
 *
 * It is produced only by `Registry::visible`, so the list the model sees is a real subset of what exists rather than a promise in a prompt.
 */
export interface ToolDescriptor {
  /**
   * Whether the tool's effect is all-or-nothing.
   */
  atomic: boolean;
  /**
   * What it does, in the model's context window.
   */
  description: string;
  /**
   * JSON Schema for the input. Validated at the dispatch boundary, never by the provider.
   */
  input_schema: {
    [k: string]: unknown;
  };
  /**
   * The form the model should emit: the short name where it is unambiguous within this scope, the full `ext.name` where it is not.
   */
  name: string;
  [k: string]: unknown;
}
