#!/usr/bin/env node
/**
 * Regenerate landing/sitemap.xml from the HTML pages actually present in
 * landing/.
 *
 * `<lastmod>` is the commit date of each page's last change (`git log -1
 * --format=%cs`), not the file mtime — a fresh clone would otherwise stamp
 * every page with checkout day. Pages that git does not know about yet
 * (uncommitted new files) fall back to their mtime so the sitemap is still
 * valid before the first commit.
 *
 * 404.html is excluded on purpose: it is an error page, never an indexable URL.
 *
 * Run it whenever a page is added/renamed:
 *   node scripts/landing/gen-sitemap.mjs
 *
 * e2e/landing-agent-readiness.spec.ts fails if a page exists without an entry,
 * which is what keeps the committed XML honest.
 */
import { execFileSync } from "node:child_process";
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const LANDING = resolve(HERE, "../../landing");
const ORIGIN = "https://orrery.kouji.dev";

/** Error pages are not URLs a crawler should index. */
const EXCLUDE = new Set(["404.html"]);

/** index.html is the site root; every other page keeps its filename. */
const pathFor = (file) => (file === "index.html" ? "/" : `/${file}`);

/** Home first, then the rest alphabetically — stable output across machines. */
const order = (a, b) =>
  a === "index.html" ? -1 : b === "index.html" ? 1 : a.localeCompare(b);

const ROOT = resolve(HERE, "../..");
const git = (...args) => execFileSync("git", args, { cwd: ROOT, encoding: "utf8" }).trim();
const mtime = (file) => statSync(join(LANDING, file)).mtime.toISOString().slice(0, 10);

/**
 * Last commit date (YYYY-MM-DD) of a page — except when the working tree holds
 * uncommitted edits to it, in which case the mtime is the truthful answer.
 * Without that branch, regenerating alongside an edit would publish the date of
 * the *previous* change. Falls back to mtime outside a git checkout.
 */
function lastmod(file) {
  try {
    if (git("diff", "--name-only", "HEAD", "--", `landing/${file}`)) return mtime(file);
    const committed = git("log", "-1", "--format=%cs", "--", `landing/${file}`);
    if (committed) return committed;
  } catch {
    /* not a git checkout — fall through to mtime */
  }
  return mtime(file);
}

const pages = readdirSync(LANDING)
  .filter((f) => f.endsWith(".html") && !EXCLUDE.has(f))
  .sort(order);

const urls = pages
  .map((f) => `  <url>\n    <loc>${ORIGIN}${pathFor(f)}</loc>\n    <lastmod>${lastmod(f)}</lastmod>\n  </url>`)
  .join("\n");

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/landing/gen-sitemap.mjs — do not hand-edit. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;

writeFileSync(join(LANDING, "sitemap.xml"), xml);
console.log(`sitemap.xml — ${pages.length} url(s): ${pages.map(pathFor).join(", ")}`);
