//! `harness/protocol` regenerated from the `orrery-proto` schemars derives.
//!
//! One source of truth, in Rust. The JSON Schema is needed anyway — for
//! `ToolDef` input validation, for `ParamSchema<P>` and for the promise that a
//! third party can build against a published spec — so the TypeScript is a
//! by-product of it rather than a second generator that could disagree with the
//! first. That is why this is neither `ts-rs` nor `specta`.
//!
//! Both outputs are committed, and [`check`] compares a fresh generation with
//! what is on disk byte for byte. CI runs it; so does `cargo test -p xtask`.

use std::path::{Path, PathBuf};
use std::process::Command;

use orrery_proto::{
    Budget, Event, Grant, LoadOutcome, Message, Request, Surface, SurfacePatch, ToolDescriptor,
    Usage,
};

/// The version of the TypeScript emitter, pinned.
///
/// Unpinned, a patch release that changes one blank line turns the drift gate
/// red on an unrelated pull request, and the next person learns to ignore it.
const JSON2TS: &str = "json-schema-to-typescript@16.0.0";

/// The banner both generated files carry.
const BANNER: &str = "/* eslint-disable */\n/**\n * Generated by `cargo xtask typegen` from \
                      harness/core/crates/orrery-proto.\n * Do not edit by hand: CI regenerates \
                      this file and fails on a diff.\n */";

/// The root the schema is generated from.
///
/// Every type a client has to name, reachable from one place. schemars walks it
/// and emits each reachable type once, under `definitions`, so the field names
/// here are an index and nothing ever serialises as a `Protocol`.
#[derive(schemars::JsonSchema)]
#[allow(dead_code)]
#[schemars(rename = "Protocol")]
struct Protocol {
    request: Request,
    event: Event,
    surface: Surface,
    surface_patch: SurfacePatch,
    grant: Grant,
    budget: Budget,
    usage: Usage,
    message: Message,
    load_outcome: LoadOutcome,
    tool_descriptor: ToolDescriptor,
}

/// The file names written into `harness/protocol`.
pub const SCHEMA_FILE: &str = "protocol.schema.json";
/// The TypeScript declarations written into `harness/protocol`.
pub const TYPES_FILE: &str = "protocol.d.ts";

/// Where the generated files live, relative to the repo root.
#[must_use]
pub fn out_dir(root: &Path) -> PathBuf {
    root.join("harness/protocol")
}

/// The JSON Schema, as it should appear on disk.
///
/// Deterministic: `schemars` keeps its definitions in a `BTreeMap` and
/// `serde_json` writes object keys in order, so two runs of the same code
/// produce the same bytes. Without that the drift gate flaps and stops meaning
/// anything.
#[must_use]
pub fn schema() -> String {
    let schema = schemars::schema_for!(Protocol);
    let mut out = serde_json::to_string_pretty(&schema).expect("a schema always serialises");
    out.push('\n');
    out
}

/// Generate both files into `dir`, creating it if needed.
///
/// # Errors
///
/// When the directory cannot be written, or the TypeScript emitter is missing
/// or fails.
pub fn write_to(dir: &Path) -> Result<(), String> {
    std::fs::create_dir_all(dir).map_err(|e| format!("could not create {}: {e}", dir.display()))?;

    let schema_path = dir.join(SCHEMA_FILE);
    std::fs::write(&schema_path, schema())
        .map_err(|e| format!("could not write {}: {e}", schema_path.display()))?;

    let types_path = dir.join(TYPES_FILE);
    run_json2ts(&schema_path, &types_path)
}

fn pnpm() -> &'static str {
    // On Windows `pnpm` is a `.cmd` shim, which `CreateProcess` will not find
    // by the bare name.
    if cfg!(windows) { "pnpm.cmd" } else { "pnpm" }
}

fn run_json2ts(schema_path: &Path, types_path: &Path) -> Result<(), String> {
    // Note: no `--bannerComment`. On Windows `pnpm` is a `.cmd` shim, and Rust
    // refuses to pass an argument containing a newline to a batch file — so the
    // banner is swapped in afterwards, in `rebanner`, rather than handed over
    // as a multi-line argument.
    let out = Command::new(pnpm())
        .arg("dlx")
        .arg(format!("--package={JSON2TS}"))
        .arg("json2ts")
        .arg("--input")
        .arg(schema_path)
        .arg("--output")
        .arg(types_path)
        .output()
        .map_err(|e| {
            format!(
                "could not run `{} dlx --package={JSON2TS} json2ts`: {e} — \
                 typegen needs pnpm on PATH",
                pnpm()
            )
        })?;
    if !out.status.success() {
        return Err(format!(
            "json2ts failed:\n{}",
            String::from_utf8_lossy(&out.stderr).trim()
        ));
    }
    rebanner(types_path)
}

/// Replace json2ts's own banner with ours, and normalise the line endings.
///
/// Both matter for the drift gate: the emitter's banner is about the emitter,
/// not about where these types come from, and a CRLF on one machine against an
/// LF on another is a byte-for-byte difference that has nothing to do with the
/// protocol.
fn rebanner(types_path: &Path) -> Result<(), String> {
    let raw = std::fs::read_to_string(types_path)
        .map_err(|e| format!("could not read {}: {e}", types_path.display()))?;
    // json2ts writes two leading comment blocks: an eslint pragma and its own
    // "automatically generated" note. Strip every leading block, not just the
    // first.
    let mut body = raw.as_str().trim_start();
    while body.starts_with("/*") {
        match body.find("*/") {
            Some(end) => body = body[end + 2..].trim_start(),
            None => break,
        }
    }
    let out = format!("{BANNER}\n\n{}", body.replace("\r\n", "\n"));
    std::fs::write(types_path, out)
        .map_err(|e| format!("could not write {}: {e}", types_path.display()))
}

/// A committed file that no longer matches what the generator produces.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Drift {
    /// Which file.
    pub file: String,
    /// What is wrong with it.
    pub detail: String,
}

impl std::fmt::Display for Drift {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}: {}", self.file, self.detail)
    }
}

/// Regenerate into a scratch directory and compare with what is committed.
///
/// # Errors
///
/// When generation itself fails. A *difference* is not an error: it comes back
/// as a non-empty vector, so the caller decides whether that is a red build or
/// a prompt to re-run `cargo xtask typegen`.
pub fn check(root: &Path) -> Result<Vec<Drift>, String> {
    let committed = out_dir(root);
    let scratch = std::env::temp_dir().join(format!("orrery-typegen-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&scratch);
    write_to(&scratch)?;

    let mut drift = Vec::new();
    for file in [SCHEMA_FILE, TYPES_FILE] {
        let fresh = std::fs::read(scratch.join(file))
            .map_err(|e| format!("the generator did not produce {file}: {e}"))?;
        match std::fs::read(committed.join(file)) {
            Err(e) => drift.push(Drift {
                file: file.to_owned(),
                detail: format!("not committed ({e}) — run `cargo xtask typegen`"),
            }),
            Ok(on_disk) if on_disk != fresh => drift.push(Drift {
                file: file.to_owned(),
                detail: format!(
                    "differs from the generator ({} bytes committed, {} generated) — \
                     run `cargo xtask typegen`",
                    on_disk.len(),
                    fresh.len()
                ),
            }),
            Ok(_) => {}
        }
    }

    let _ = std::fs::remove_dir_all(&scratch);
    Ok(drift)
}

/// Regenerate `harness/protocol` in place.
///
/// # Errors
///
/// When generation fails.
pub fn run(root: &Path) -> Result<PathBuf, String> {
    let dir = out_dir(root);
    write_to(&dir)?;
    Ok(dir)
}
